// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgabvcthiammwjnshdsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnYWJ2Y3RoaWFtbXdqbnNoZHNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTQxNDksImV4cCI6MjA2NjU5MDE0OX0.0osWfLKgbiJZSRjTccsnFWMsdDK3cyJgWdNkLbjXeZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);